config/routes.rb
Rails.application.routes.draw do

  root 'cars#index'

  resources :cars do          # for individual cars
    member do
      get 'claim' => 'cars#claim'
    end

    member do
      get 'unclaim' => 'cars#unclaim'
    end

  end

  resources :users,
    only: [:new, :create],
    path_names: { new: 'signup' }

  get '/login',
    to: 'sessions#login',
    as: 'login'

  post '/login' => 'sessions#create'

  get '/my_cars',
      to: 'cars#my_cars'

  delete '/logout',
    to: 'sessions#destroy'

end

app/models/car.rb
class Car < ActiveRecord::Base
  validates :make, :model, :year, :price, presence: true
  validates :price,
    numericality: {
    greater_than: 0.00,
    less_than: 1_000_000
  }
  validates :year, inclusion: 1769..Time.zone.now.year

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validate :password, presence: true

  has_many :cars
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy, :claim, :unclaim]

  def claim
    if current_user
    # @car.user = current_user  -- another option
      current_user.cars << @car
    end
    redirect_to root_path, notice: "#{@car.make} #{@car.model} has been moved to your inventory."
  end

  def unclaim
    return unless current_user
    @car.user_id = nil
    @car.save
    redirect_to my_cars_path, notice: "#{@car.make} #{@car.model} has been moved out of your inventory."
  end


  def index
    @cars = Car.where(user_id: nil).paginate( page: params[:page], per_page: 20)
  end

  def my_cars
    @cars = current_user.cars.paginate( page: params[:page], per_page: 20)
    render :index
  end

  def new
    @car = Car.new
  end

  def edit

  end

  def show

  end

  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  def create
    @car = Car.new(car_params)
    creation_message = "#{@car.year} #{@car.make} #{@car.model} has been created."

    if @car.save
      redirect_to root_path, notice: creation_message
    end
  end

  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    def car_params
      params.require(:car).permit(:make, :model, :year, :price)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      # user submitted valid password
      session[:user_id] = user.id
      redirect_to root_path, notice: "Welcome back #{user.first_name}"
    else
      flash[:error] = "Oops, something went wrong. Try again."
      render :login
    end
  end

  def destroy
    user = current_user
    session[:user_id] = nil
    redirect_to root_path,
      notice: "See you next time #{user.email}"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path,
        notice: "Thank you for signing up #{@user.first_name.capitalize}."
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cars/_form.html.erb
<%= form_for(@car, :html => { :class => "form-horizontal" }) do |f| %>
  <% if @car.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h4>

      <ul>
        <% @car.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :model, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :model, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :make, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :make, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :year, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :year, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :price, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :price, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-success" %>
    </div>
  </div>
<% end %>
<div class="form-group">
  <div class="col-sm-offset-2 col-sm-10">
    <%= link_to 'Back', root_path, :class => "btn btn-primary" %>
  </div>
</div>

app/views/cars/edit.html.erb
<h2>Editing a car</h2>

<%= render 'form' %>

<%= link_to 'Back', car_path %>

app/views/cars/index.html.erb
<div class="page-header">
  <%= link_to new_car_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Car
  <% end %>
  <h1>See our selection of cars below</h1>
</div>

<%= will_paginate @cars, renderer: BootstrapPagination::Rails %>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
    <tr>
      <th>Model</th>
      <th>Make</th>
      <th>Year</th>
      <th>Price</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
    </thead>

    <tbody>
    <%= content_tag_for(:tr, @cars) do |car| %>
      <td><%= car.model %></td>
      <td><%= car.make %></td>
      <td><%= car.year %></td>
      <td><%= number_to_currency(car.price) %></td>
      <% if current_user %>
        <td><%= link_to 'Claim', claim_car_path(car) %></td>
        <td><%= link_to 'Unclaim', unclaim_car_path(car) %></td>
    <% end %>
      <td><%= link_to 'Show', car %></td>
      <td><%= link_to 'Edit', edit_car_path(car) %></td>
      <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
    </tbody>
  </table>
</div>

app/views/cars/new.html.erb
<h2>New Car</h2>

<%= render 'form' %>

app/views/cars/show.html.erb
<table>
  <thead>
  <tr>
    <th>Make</th>
    <th>Model</th>
    <th>Year</th>
    <th>Price</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
     <tr>
      <td><%= @car.make %></td>
      <td><%= @car.model %></td>
      <td><%= @car.year %></td>
      <td><%= @car.price %></td>
    </tr>
  </tbody>
</table>

<%= link_to 'Edit', edit_car_path(@car) %>
<%= link_to 'Destroy', @car, method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to 'Home', cars_path %>

app/views/layouts/_authentication.html.erb
<% if current_user %>
  <li>Signed in as <%= current_user.email %></li>
  <li><%= link_to 'Logout', logout_path, method: :delete %></li>
  <li><%= link_to 'My Cars', my_cars_path %></li>
<% else %>
  <li><%= link_to 'Signup', new_user_path %></li>
  <li><%= link_to 'Login', login_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DavinciMotors</title>
  <meta charset="utf-8">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js", "https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js" %>

  <%= csrf_meta_tags %>


  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta name="description" content="">
  <meta name="author" content="">

</head>
<body>

  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "DaVinci Motors", "/", :class => "navbar-brand" %>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <%= render 'layouts/authentication' %>
        </ul>
      </div>
    </div>
  </div>


<div class="container">

  <% flash.each do |name, msg| %>
    <%= content_tag :div, :class => "alert alert-#{ name.to_sym == :error ? "danger" : "success" } alert-dismissable" do %>
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= msg %>
    <% end %>
  <% end %>

  <%= yield %>
</div>
</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user, :html => { :class => "form-horizontal" }) do |f| %>
  <% if @user.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4>Hmmm...looks like you need to fix <%= pluralize(@user.errors.count, "error") %></h4>

      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :first_name, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :first_name, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :last_name, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :last_name, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :email, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :password, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.password_field :password, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.password_field :password_confirmation, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit 'Signup', :class => "btn btn-success" %>
    </div>
  </div>
<% end %>

app/views/users/new.html.erb
<h2>New User</h2>

<%= render 'form' %>

<div class="form-group">
  <div class="col-sm-offset-2 col-sm-10">
    <%= link_to 'Back', root_path, :class => "btn btn-primary" %>
  </div>
</div>